canonical/data-science-stack

- src/dss/config.py
- src/dss/initialize.py
- src/dss/manifest_templates/dss_core.yaml.j2
- src/dss/manifest_templates/mlflow_deployment.yaml.j2
- src/dss/utils.py
- tests/integration/test_dss.py
- tests/unit/test_initialize.py
* Moves constants to the shared `config.py` file so their definitions are shared
* moves the `manifests.yaml` for dss's namespace + mlflow deployment to a `manifest_templates` directory and splits the namespace out from the mlflow resources
* adds templating to the existing manifests to remove hardcoded values
* removes a leftover, unused fixture
> Refactor `dss initialize` to make code easier to reuse

- snap/snapcraft.yaml
- snapcraft.yaml
feat: add dss snap project
This commit adds the snap project for DSS.
Fixes #25
1. Clone this repository and build the snap
```
snapcraft
```
2. Install the snap `snap install <name of snap>.snap --dangerous `
3. Run `dss` and see the help printed out:
```
$ dss
Usage: dss [OPTIONS] COMMAND [ARGS]...
Command line interface for managing the DSS application.
Options:
--help  Show this message and exit.
Commands:
create-notebook  Create a Notebook server.
initialize       Initialize DSS on the given Kubernetes cluster.
```
> feat: add dss snap

- snapcraft.yaml
No point in building for every arch on every commit using the snapcraft build service.
> This snap is arch=any so lets only build on amd64

- setup.cfg
With this fix all the manifests in the dss/manifest_templates folder will be included in the dss librarry. 
This PR fixes a problem mentioned in https://github.com/canonical/data-science-stack/issues/44
> Include all manifests into dss python librarry

- src/dss/main.py
- src/dss/status.py
- src/dss/utils.py
- tests/integration/test_dss.py
- tests/unit/test_status.py
- tests/unit/test_utils.py
Resolves: https://github.com/canonical/data-science-stack/issues/67
The nvidia gpu status was tested only on my local machine as the runners don't have gpus.
**Steps to test locally:** 
Install and setup microk8s 
```
sudo snap install microk8s --channel=1.28/stable --classic
microk8s enable storage dns rbac gpu
microk8s config > ~/.kube/config
```
Run dss
```
export KUBECONFIG=~/.kube/config
pip install .
dss initialize --kubeconfig $KUBECONFIG
dss status
```
> feat: implement dss status

- src/dss/main.py
- src/dss/purge.py
- src/dss/utils.py
- tests/integration/test_dss.py
- tests/unit/test_create_notebook.py
- tests/unit/test_purge.py
- tests/unit/test_utils.py
* Implement `dss purge` command
* Use `dss purge` to clean up integration tests (and thus test that it
works as expected).
* Add unit tests for `purge` function and helper functions.
Closes #34
Given that microk8s is already installed, run dss
```
git checkout origin/kf-5383-feat-dss-purge-command
pip install .
dss initialize --kubeconfig ~/.kube/config
dss create test-notebook
dss purge --kubeconfig ~/.kube/config
```
```bash
kubectl get ns
kubectl get po -n dss
kubectl get pvc -n dss
```
> feat: Implement `dss purge` command

- snapcraft.yaml
Change the snap name to `data-science-stack`.
For local testing don't forget to create the alias.
```
snapcraft
snap install data-science-stack_<name>.snap --dangerous
sudo snap alias  data-science-stack.dss dss
dss --help
```
> Change snap name to `data-science-stack`

- src/dss/create_notebook.py
- src/dss/logs.py
- src/dss/main.py
- src/dss/remove_notebook.py
- src/dss/status.py
- src/dss/stop.py
- tests/unit/test_create_notebook.py
- tests/unit/test_logs.py
- tests/unit/test_remove_notebook.py
- tests/unit/test_stop.py
closes #78 
**Note: Integration tests in the CI are failing due to https://github.com/microsoft/linux-package-repositories/issues/130, but they can be run locally with `tox -e integration`**
Refactors the following `dss` commands:
* `create`
* `initialize`
* `logs`
* `remove`
* `status`
* `stop`
With the following changes:
1. use `logger.debug` to store the error with traceback
2. exit with `1` exit code in failure cases
3. raise `RuntimeError` in failure cases inside the module function
4. handle `RuntimeError` in main without logging anything else, just by exiting with status code 1 (logging was done in the module function)
5. handle any other `Exception` in main by providing descriptive error message and use debug to store error and traceback and exit with status code 1.
This PR …
> Refactor `dss` commands exit codes and logging

- docs/index.rst
The build in readthedocs is failing with the following message
https://readthedocs.com/projects/canonical-data-science-stack/builds/2173740/
```
Running Sphinx v7.3.7
matplotlib is not installed, social cards will not be generated
making output directory... done
myst v3.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions={'substitution', 'deflist', 'linkify'}, disable_syntax=[], all_links_external=False, links_external_new_tab=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, …
```
> docs: Remove warnings by fixing title underline

- poc/intel/README.md
This adds a section to the Intel PoC README as a follow up to some troubleshooting work performed on systems containing both a NVIDIA dGPU + Intel CPU+iGPU.
> Intel PoC README: add caveat for multi-gpu systems

- docs/how-to/jupyter-notebook/notebook-logs.rst
We saw the docs failing in https://github.com/canonical/data-science-stack/pull/112 because of the following error
```
/home/docs/checkouts/readthedocs.org/user_builds/canonical-data-science-stack/checkouts/latest/docs/how-to/jupyter-notebook/notebook-logs.rst:51: WARNING: Enumerated list ends without a blank line; unexpected unindent.
```
This was because of https://github.com/canonical/data-science-stack/pull/109
It looks like ReadTheDocs sometimes failed to build, even though the existing CI was passing. I've extended now the CI to also build with readthedocs so we can capture such errors in the future
https://library.canonical.com/documentation/publish-on-read-the-docs#enable-pr-previews-7
> docs: Fix the list

- src/dss/manifest_templates/notebook_deployment.yaml.j2
partialy resolves: https://github.com/canonical/data-science-stack/issues/102 
this resolution was agreed to take for version 1.
based on the comment we will mount pvc to shared instead of the home folder.
> Mounts shared pvc to shared folder.

- docs/how-to/dss/initialize-dss.rst
- docs/reference/enable-gpu.rst
- docs/tutorial/getting-started.rst
Right now the docs are not using `sudo` for the MicroK8s commands, neither inform users to set the groups for using the `microk8s` commands without sudo
https://microk8s.io/docs/getting-started
The above will result in errors in both
1. Initialising the MicroK8s addons (dns, gpu)
2. The DSS CLI won't be able to connect to microK8s
The PR adds `sudo` to the commands, since this is also the long term approach the K8s team will take for the new K8s cli as well.
> docs: Use sudo in MicroK8s commands

- docs/tutorial/getting-started.rst
The `storage` addon is deprecated and will be removed, prefer `hostpath-storage`.
When following the tutorial, the logs show:
```
ubuntu@dev:~$ sudo snap install microk8s --channel 1.28/stable --classic
sudo microk8s enable storage dns rbac
microk8s (1.28/stable) v1.28.12 from Canonical✓ installed
Infer repository core for addon storage
Infer repository core for addon dns
Infer repository core for addon rbac
WARNING: Do not enable or disable multiple addons in one command.
This form of chained operations on addons will be DEPRECATED in the future.
Please, enable one addon at a time: 'microk8s enable <addon>'
DEPRECATION WARNING: 'storage' is deprecated and will soon be removed. Please use 'hostpath-storage' instead.
Infer repository core for addon hostpath-storage
Enabling default storage …
```
> docs: `s/storage/hostpath-storage` in tutorial for MicroK8s

- src/dss/status.py
- src/dss/utils.py
- tests/unit/test_status.py
closes #146
* log Intel GPU status in `dss status`
* add unit tests to include Intel GPU status
* refactor NVIDIA part in `dss status` to differentiate between Intel and NVIDIA GPUs
> Update `dss status` to show intel GPU status

- src/dss/config.py
- src/dss/create_notebook.py
- src/dss/manifest_templates/notebook_deployment.yaml.j2
- src/dss/utils.py
- tests/unit/test_create_notebook.py
This commit introduces an automatic way of scheduling Notebook Servers on Nodes labeled as intel.feature.node.kubernetes.io/gpu.
This commit also affects the command and args that run for the Notebook Servers containers, as these are now part of the requirements for making Intel GPUs work. They should be exactly as [this](https://github.com/canonical/data-science-stack/blob/frenchwr/intel-gpu-integration/src/dss/manifest_templates/notebook_deployment.yaml.j2#L29C1-L43C39).
Fixes #147
Assuming you have a microk8s cluster with hostpath-storage enabled
1. Clone this repository, checkout to the branch of this PR
2. Build and install from source `pip install .`
3. Initialise `dss initialize --kubeconfig="$(sudo microk8s config)"`
4. Label the node to simulate the Intel plugin has done its job …
> feat: update create command to support Intel GPU notebooks

- docs/.custom_wordlist.txt
- docs/how-to/jupyter-notebook.rst
- docs/reuse/links.txt
closes #149 
Note to reviewer: I'm referencing the guide from PR #160 that is not merged yet so the documentation build is expected to fail
> docs: Add how-to guide to create Intel Notebook 

- docs/how-to/dss.rst
- docs/how-to/enable-gpus/enable-intel-gpu.rst
- docs/how-to/enable-gpus/enable-nvidia-gpu.rst
- docs/how-to/jupyter-notebook.rst
- docs/how-to/mlflow.rst
- docs/tutorial/getting-started.rst
- src/dss/logger.py
- tests/unit/test_logger.py
Closes: https://github.com/canonical/data-science-stack/issues/158
- Removing `[INFO] ` prefix from stdout logs. We want to keep it in the logs file. 
- Changing docs to reflwct the change
- Adding unit tests for logger
How to test:
```
git clone <repo>
cd <repo>
pip install .
dss status
```
The logs in console should not have `[INFO]`
> Remove `[INFO]` prefix from stdout logs

- src/dss/utils.py
Closes: https://github.com/canonical/data-science-stack/issues/159
Because there is shared function for waiting for any deployment to be ready we only had to change code in one place :) 
Manual test:
```
git clone <repo>
cd <repo>
pip install .
dss initialize --kubeconfig="$(sudo microk8s config)"
dss create my-notebook --image=pytorch
```
The message `Waiting for deployment <deployment-name> in namespace dss to be ready...` should appear only once in both cases.
> Remove repeated output while waiting for deployment

- docs/how-to/enable-gpus/enable-intel-gpu.rst
Closes: https://github.com/canonical/data-science-stack/issues/167
Adds note about micork8s kubeconfig initialisation in the docs
> Add note to docs for microk8s kubeconfig initialisation for kubectl snap

- docs/index.rst
Revisit homepage grid to left align the Explanation section.
> docs: minor tweak homepage grid left aligning

- tests/integration/test_dss.py
> Remove assertion that GPU acceleration is disabled in CPU tests

- poc/common-manifests/mlflow.yaml
- poc/common-manifests/notebooks.yaml
- src/dss/manifest_templates/dss_core.yaml.j2
- src/dss/manifest_templates/mlflow_deployment.yaml.j2
Closes: https://github.com/canonical/data-science-stack/issues/193
This PR is merged against dev branch for Canonical k8s integration. There are some other tasks which needs to be finished before merging to main. 
This change could be only tested manually. Tests are supposed to fail.
1. Deploy caonical k8s 
```
sudo snap install k8s --classic
```
2. Bootstrap
```
sudo k8s bootstrap
```
3. According to [documentation](https://documentation.ubuntu.com/canonical-kubernetes/latest/src/snap/tutorial/getting-started/#enable-local-storage) they recommend to enable local storage 
```
sudo k8s enable local-storage
```
4. Go to this repo and pack the snap 
```
snapcraft
```
5. You should be prompted with the snap file which we will now deploy to your computer.
```
sudo snap install …
```
> Fix MLflow deployment for Canonical k8s

- .github/concierge.yaml
- .github/workflows/build_and_test_snap.yaml
- .github/workflows/tests.yaml
This PR is part of https://github.com/canonical/data-science-stack/issues/198 and https://github.com/canonical/data-science-stack/issues/197
Changes:
- Install canonical k8s 
- Install Nvidia k8s operator
- Run integration tests
> feat: run integration tests on canonical k8s

- docs/explanation/dss-arch.rst
- docs/how-to/dss.rst
- docs/how-to/enable-gpus/enable-intel-gpu.rst
- docs/how-to/enable-gpus/enable-nvidia-gpu.rst
- docs/how-to/jupyter-notebook.rst
- docs/how-to/mlflow.rst
- docs/index.rst
- docs/reuse/links.txt
- docs/tutorial/get-started.rst
This PR addresses and **closes [#200](https://github.com/canonical/data-science-stack/issues/200)** by replacing all references to **MicroK8s** with **Canonical K8s** across the documentation. Additionally, the sections related to accessing host path storage data have been removed where applicable.
- Updated installation, initialization, and management steps to reflect Canonical K8s (`manage_DSS.rst`, `tutorial.rst`).
- Adjusted GPU-related setup instructions for NVIDIA and Intel to align with Canonical K8s (`enable_gpu.rst`, `enable_intel_gpu.rst`).
- Revised the DSS architecture overview to reflect the new orchestration system (`dss_architecture.rst`).
- Removed host path storage access sections (`manage_notebooks.rst`).
- Updated the home and general structure files to ensure …
> feat: update docs for canonical k8s

- src/dss/manifest_templates/notebook_deployment.yaml.j2
Closes: https://github.com/canonical/data-science-stack/issues/209
Manual test: 
1. Deploy caonical k8s 
```
sudo snap install k8s --classic
```
2. Bootstrap
```
sudo k8s bootstrap
```
3. According to [documentation](https://documentation.ubuntu.com/canonical-kubernetes/latest/src/snap/tutorial/getting-started/#enable-local-storage) they recommend to enable local storage 
```
sudo k8s enable local-storage
```
4. Go to this repo and pack the snap 
```
snapcraft
```
5. You should be prompted with the snap file which we will now deploy to your computer.
```
sudo snap install data-science-stack_0.1-<hash>_amd64.snap --dangerous
```
6. Initialise the DSS 
```
data-science-stack.dss initialize --kubeconfig="$(echo "$(sudo k8s config)")"
```
7. Now create an example notebook 
``` …
```
> fix: use security context for the mounted volumens

- src/dss/utils.py
There are a number of factors that could cause initialize to take more than 180 seconds. I think it's reasonable to extend that timeout.
> Bump timeout to 600 seconds, 180 often caused timeout errors

- docs/custom_conf.py
Fixing two broken links reported in the Docs checks and adding slug to avoid 404 reports in documentation.ubuntu.com
> docs: fixing broken links and 404 reports

- docs/custom_conf.py
Causes documentation to deploy a sitemap using the sphinx-sitemap extension for documentation discovery from the parent project.
> feat: sitemap generation
